var urlBase = "https://api.dataon.com.br/v2/api/";
var token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6InN1cG9ydGU0IiwidXNlck5hbWUiOiJzdXBvcnRlNCIsImhhc2giOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJkYXRlUmVnaXN0ZXIiOiIwOS8xMC8yMDI0IDEzOjM4OjU1IiwiZG9JZCI6IjM1OTIiLCJleHAiOjE3Mjg1NzgzMzV9.zw66AdJUejt_3kYJfba9hse76EcNgKICH8PRFDfTS8U';
var basicToken = 'Basic ZGF0YW9uOkRhdGFPbkFQSUAj';

module.exports = {token,urlBase,basicToken}